name: content-hub
version: 0.2
summary: content sharing/picking service
description: |
  Content sharing/picking infrastructure and service, designed to allow apps to
  securely and efficiently exchange content.
  Please find the source code at:
  https://code.launchpad.net/content-hub
confinement: strict

apps:
  content-hub:
    command: desktop-launch content-hub-service
    slots: [content-transfer]
    plugs: [gsettings, dbus]

plugs:
  dbus:
    name: com.ubuntu.content.dbus.Service
    bus: session

parts:
  content-hub:
    plugin: cmake
    source: .

    build-packages:
      - build-essential
      - cmake
      - dbus-test-runner
      - dh-apparmor
      - dh-translations
      - doxygen
      - google-mock
      - lcov
      - libapparmor-dev
      - libglib2.0-dev
      - libgsettings-qt-dev
      - liblibertine-dev
      - libmirclient-dev
      - libnih-dbus-dev
      - libnotify-dev
      - libubuntu-download-manager-client-dev
      - libubuntu-app-launch3-dev
      - qt5-default
      - qtbase5-dev
      - qtdeclarative5-dev
      - qtdeclarative5-dev-tools
      - qtdeclarative5-qtquick2-plugin
      - qtdeclarative5-test-plugin
      - qtdeclarative5-ubuntu-ui-toolkit-plugin
      - qttools5-dev-tools

    stage-packages:
      - libmirclient9
      - libgsettings-qt1
      - libglib2.0-bin

    configflags:
      - -DCMAKE_INSTALL_PREFIX:PATH=/usr
      - -DCMAKE_LIBRARY_PATH=/usr/lib

    filesets:
      unwanted:
        # Files that we don't want/need in the final snap package
        - -etc
        - -usr/bin/content-hub-test*
        - -usr/include
        - -usr/lib/debug
        - -usr/lib/*/libogg*
        - -usr/lib/*/libpulse*
        - -usr/lib/*/qt5
        - -usr/lib/*/pkgconfig
        - -usr/lib/python*
        - -usr/share/applications
        - -usr/share/apport
        - -usr/share/bug
        - -usr/share/doc
        - -usr/share/fonts
        - -usr/share/libwacom
        - -usr/share/lintian
        - -usr/share/man
        - -usr/share/X11
        - -usr/lib/*.a
        - -usr/lib/*/*.a
        - -usr/lib/*.la
        - -usr/lib/*/*.la
        - -usr/lib/*/*.o

    prime:
      - $unwanted

    after:
      - desktop-ubuntu-app-platform
