#!/bin/sh

# start X
(Xvfb :5 >/dev/null 2>&1 &)
XVFB_PID=$!
export DISPLAY=:5

# start local session D-BUS
eval `dbus-launch`
trap "kill $DBUS_SESSION_BUS_PID $XVFB_PID" 0 TERM QUIT INT
export DBUS_SESSION_BUS_ADDRESS
export XAUTHORITY=/dev/null

FAILED=""

content-hub-test-sharer &2>/dev/null
content-hub-send "content:?pkg=content-hub-test-sharer&handler=share&text=text" 2>/dev/null
if [ $? -ne 0 ]; then
    FAILED="$FAILED share"
fi

content-hub-test-importer &2>/dev/null
content-hub-send "content:?pkg=content-hub-test-importer&handler=export&text=text" 2>/dev/null
if [ $? -ne 0 ]; then
    FAILED="$FAILED import"
fi

if [ -z "$FAILED" ]; then
    echo "All tests passed"
    exit 0
else
    echo "$FAILED failed"
    exit 1
fi

