usr/bin/content-hub-peer-picker
usr/bin/content-hub-send
usr/bin/content-hub-service
usr/lib/*/ubuntu-app-launch
usr/lib/systemd/user
usr/share/dbus-1
usr/share/glib-2.0/schemas
usr/share/locale/*/LC_MESSAGES/content-hub.mo
usr/share/applications/content-hub-send.desktop
usr/share/applications/content-hub-peer-picker.desktop
usr/share/url-dispatcher/urls/content-hub-send.url-dispatcher
usr/share/content-hub/icons
debian/apparmor/content-hub-peer-picker etc/apparmor.d
